# version : '3.9'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-master}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v2.2.js}"
                AGENT_BRANCH: "${AGENT_BRANCH:-master}"
            shm_size: "5gb"
        shm_size: "5gb"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
            SYMBOLIC_AGENT_DIR: "/app/SymbolicAIAgent"
            OLLAMA_HOST: "http://host.docker.internal:11434"
            DEBUG_KQML: "true"  # or "false" # <- flag to enable debug logging of KQML messages from the symbolic agent (during chat phase)
            ROUTE: "route1"  # or "route2" <- flag to select flow variant (route1, route2, etc.)
        ports:
            - "80:5000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - data:/app/data
volumes:
  data:
        
